
- name: install epel-release (CentOS)
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: install monit
  yum:
    name: monit
    state: present
    update_cache: yes

- name: Enable service monit
  service:
    name: monit
    enabled: yes
