
- name: install epel-release (CentOS)
  yum:
    name: epel-release
    state: present
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: install monit
  yum:
    name: monit
    state: present
    update_cache: yes
