---


- block:
  - include_tasks: "{{ ansible_distribution }}-install.yml"
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS"

  - setup:
      filter: "ansible_hostname"

  - name: copy notification_by_slack.sh
    template:
      src: notification_by_slack.sh
      dest: /usr/local/bin/notification_by_slack.sh
      mode: 0711
    when: slack_hook_url is defined
  become: yes
  tags:
    - install

- name: setup monit
  block:
    - name: get monitrc path
      set_fact:
        monitrc_path: "{{ monitrc_path[item] }}"
      with_items:
        - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}"

    - name: get monit config path
      set_fact:
        monit_config_path: "{{ monit_config_path[item] }}"
      with_items:
        - "{{ ansible_distribution }}"

    - name: set monitrc (custom)
      copy:
        src: "{{ custom_monitrc }}"
        backup: yes
        dest: "{{ monitrc_path }}"
        group: root
        owner: root
        mode: 0600
      when: custom_monitrc is defined

    - name: set monit config (custom)
      copy:
        src: "{{ item.src }}"
        backup: yes
        dest: "{{ monit_config_path }}/{{ item.dest_filename }}"
        group: root
        owner: root
        mode: 0644
      with_items:
        - "{{ custom_monit_conf }}"
      notify: restart_monit
      when: custom_monit_conf is defined

  become: yes
  tags:
    - setup
